species_data_files += files('data.json')
species_data_files += files('forms/mega_x/data.json')
species_data_files += files('forms/mega_y/data.json')

poke_icon_files += files('icon.png')
charizard_mega_x_icon = files('forms/mega_x/icon.png')
charizard_mega_y_icon = files('forms/mega_y/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '252': files('forms/base/back.png'),
    '253': files('forms/base/front.png'),
    '254': files('forms/mega_x/back.png'),
    '255': files('forms/mega_x/front.png'),
    '256': files('forms/base/normal.pal'),
    '257': files('forms/base/shiny.pal'),
    '258': files('forms/mega_x/normal.pal'),
    '259': files('forms/mega_x/shiny.pal'),
    '262': files('forms/mega_y/back.png'),
    '263': files('forms/mega_y/front.png'),
    '266': files('forms/mega_y/normal.pal'),
    '267': files('forms/mega_y/shiny.pal'),
}
pokefoot_files += files('footprint.png')
