species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
chimecho_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '588': files('forms/base/back.png'),
    '589': files('forms/base/front.png'),
    '590': files('forms/mega/back.png'),
    '591': files('forms/mega/front.png'),
    '592': files('forms/base/normal.pal'),
    '593': files('forms/base/shiny.pal'),
    '594': files('forms/mega/normal.pal'),
    '595': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
