species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
gengar_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
        '198': files('forms/base/back.png'),
        '199': files('forms/base/front.png'),
        '200': files('forms/mega/back.png'),
        '201': files('forms/mega/front.png'),
        '528': files('forms/base/normal.pal'),
        '529': files('forms/base/shiny.pal'),
        '530': files('forms/mega/normal.pal'),
        '531': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
