#ifndef POKEPLATINUM_CONSTANTS_FORMS_H
#define POKEPLATINUM_CONSTANTS_FORMS_H

#include "constants/species.h"

#define MOVESET_FORM_DEOXYS_ATTACK   NATIONAL_DEX_COUNT + 1
#define MOVESET_FORM_DEOXYS_DEFENSE  NATIONAL_DEX_COUNT + 2
#define MOVESET_FORM_DEOXYS_SPEED    NATIONAL_DEX_COUNT + 3
#define MOVESET_FORM_WORMADAM_SANDY  NATIONAL_DEX_COUNT + 4
#define MOVESET_FORM_WORMADAM_TRASH  NATIONAL_DEX_COUNT + 5
#define MOVESET_FORM_GIRATINA_ORIGIN NATIONAL_DEX_COUNT + 6
#define MOVESET_FORM_SHAYMIN_SKY     NATIONAL_DEX_COUNT + 7
#define MOVESET_FORM_ROTOM_HEAT      NATIONAL_DEX_COUNT + 8
#define MOVESET_FORM_ROTOM_WASH      NATIONAL_DEX_COUNT + 9
#define MOVESET_FORM_ROTOM_FROST     NATIONAL_DEX_COUNT + 10
#define MOVESET_FORM_ROTOM_FAN       NATIONAL_DEX_COUNT + 11
#define MOVESET_FORM_ROTOM_MOW       NATIONAL_DEX_COUNT + 12

#define UNOWN_FORM_A     0
#define UNOWN_FORM_B     1
#define UNOWN_FORM_C     2
#define UNOWN_FORM_D     3
#define UNOWN_FORM_E     4
#define UNOWN_FORM_F     5
#define UNOWN_FORM_G     6
#define UNOWN_FORM_H     7
#define UNOWN_FORM_I     8
#define UNOWN_FORM_J     9
#define UNOWN_FORM_K     10
#define UNOWN_FORM_L     11
#define UNOWN_FORM_M     12
#define UNOWN_FORM_N     13
#define UNOWN_FORM_O     14
#define UNOWN_FORM_P     15
#define UNOWN_FORM_Q     16
#define UNOWN_FORM_R     17
#define UNOWN_FORM_S     18
#define UNOWN_FORM_T     19
#define UNOWN_FORM_U     20
#define UNOWN_FORM_V     21
#define UNOWN_FORM_W     22
#define UNOWN_FORM_X     23
#define UNOWN_FORM_Y     24
#define UNOWN_FORM_Z     25
#define UNOWN_FORM_EXC   26
#define UNOWN_FORM_QUE   27
#define UNOWN_FORM_COUNT 28

#define CASTFORM_FORM_NORMAL 0
#define CASTFORM_FORM_SUNNY  1
#define CASTFORM_FORM_RAINY  2
#define CASTFORM_FORM_SNOWY  3
#define CASTFORM_FORM_COUNT  4

#define DEOXYS_FORM_NORMAL  0
#define DEOXYS_FORM_ATTACK  1
#define DEOXYS_FORM_DEFENSE 2
#define DEOXYS_FORM_SPEED   3
#define DEOXYS_FORM_COUNT   4

#define BURMY_FORM_PLANT 0
#define BURMY_FORM_SAND  1
#define BURMY_FORM_TRASH 2
#define BURMY_FORM_COUNT 3

#define WORMADAM_FORM_PLANT 0
#define WORMADAM_FORM_SAND  1
#define WORMADAM_FORM_TRASH 2
#define WORMADAM_FORM_COUNT 3

#define CHERRIM_FORM_OVERCAST 0
#define CHERRIM_FORM_SUNSHINE 1
#define CHERRIM_FORM_COUNT    2

#define SHELLOS_FORM_WEST  0
#define SHELLOS_FORM_EAST  1
#define SHELLOS_FORM_COUNT 2

#define GASTRODON_FORM_WEST  0
#define GASTRODON_FORM_EAST  1
#define GASTRODON_FORM_COUNT 2

#define ROTOM_FORM_BASE  0
#define ROTOM_FORM_HEAT  1
#define ROTOM_FORM_WASH  2
#define ROTOM_FORM_FROST 3
#define ROTOM_FORM_FAN   4
#define ROTOM_FORM_MOW   5
#define ROTOM_FORM_COUNT 6

#define GIRATINA_FORM_ALTERED 0
#define GIRATINA_FORM_ORIGIN  1
#define GIRATINA_FORM_COUNT   2

#define SHAYMIN_FORM_LAND  0
#define SHAYMIN_FORM_SKY   1
#define SHAYMIN_FORM_COUNT 2

#define ARCEUS_FORM_COUNT 18

#define EGG_FORM_BASE    0
#define EGG_FORM_MANAPHY 1
#define EGG_FORM_COUNT   2

// Mega Evolution Forms

#define VENUSAUR_FORM_MEGA 1
#define CHARIZARD_FORM_MEGA_X 1
#define CHARIZARD_FORM_MEGA_Y 2
#define BLASTOISE_FORM_MEGA 1
#define BEEDRILL_FORM_MEGA 1
#define PIDGEOT_FORM_MEGA 1
#define RAICHU_FORM_MEGA_X 1
#define RAICHU_FORM_MEGA_Y 2
#define CLEFABLE_FORM_MEGA 1
#define ALAKAZAM_FORM_MEGA 1
#define VICTREEBEL_FORM_MEGA 1
#define SLOWBRO_FORM_MEGA 1
#define GENGAR_FORM_MEGA 1
#define KANGASKHAN_FORM_MEGA 1
#define STARMIE_FORM_MEGA 1
#define PINSIR_FORM_MEGA 1
#define GYARADOS_FORM_MEGA 1
#define AERODACTYL_FORM_MEGA 1
#define DRAGONITE_FORM_MEGA 1
#define MEWTWO_FORM_MEGA_X 1
#define MEWTWO_FORM_MEGA_Y 2
#define MEGANIUM_FORM_MEGA 1
#define FERALIGATR_FORM_MEGA 1
#define AMPHAROS_FORM_MEGA 1
#define STEELIX_FORM_MEGA 1
#define SCIZOR_FORM_MEGA 1
#define HERACROSS_FORM_MEGA 1
#define SKARMORY_FORM_MEGA 1
#define HOUNDOOM_FORM_MEGA 1
#define TYRANITAR_FORM_MEGA 1
#define SCEPTILE_FORM_MEGA 1
#define BLAZIKEN_FORM_MEGA 1
#define SWAMPERT_FORM_MEGA 1
#define GARDEVOIR_FORM_MEGA 1
#define SABLEYE_FORM_MEGA 1
#define MAWILE_FORM_MEGA 1
#define AGGRON_FORM_MEGA 1
#define MEDICHAM_FORM_MEGA 1
#define MANECTRIC_FORM_MEGA 1
#define SHARPEDO_FORM_MEGA 1
#define CAMERUPT_FORM_MEGA 1
#define ALTARIA_FORM_MEGA 1
#define BANETTE_FORM_MEGA 1
#define CHIMECHO_FORM_MEGA 1
#define ABSOL_FORM_MEGA 1
#define ABSOL_FORM_MEGA_Z 2
#define GLALIE_FORM_MEGA 1
#define SALAMENCE_FORM_MEGA 1
#define METAGROSS_FORM_MEGA 1
#define LATIAS_FORM_MEGA 1
#define LATIOS_FORM_MEGA 1
#define STARAPTOR_FORM_MEGA 1
#define LOPUNNY_FORM_MEGA 1
#define GARCHOMP_FORM_MEGA 1
#define GARCHOMP_FORM_MEGA_Z 2
#define LUCARIO_FORM_MEGA 1
#define LUCARIO_FORM_MEGA_Z 2
#define ABOMASNOW_FORM_MEGA 1
#define GALLADE_FORM_MEGA 1
#define FROSLASS_FORM_MEGA 1
#define HEATRAN_FORM_MEGA 1
#define DARKRAI_FORM_MEGA 1

#define NUMBER_OF_MEGAS 62

#define MOVESET_MAX MOVESET_FORM_ROTOM_MOW + NUMBER_OF_MEGAS

#endif
