#ifndef POKEPLATINUM_CONSTANTS_PALETTE_H
#define POKEPLATINUM_CONSTANTS_PALETTE_H

#define TM_PALETTE_FIGHTING 0x18E
#define TM_PALETTE_DRAGON 0x18F
#define TM_PALETTE_WATER 0x190
#define TM_PALETTE_PSYCHIC 0x191
#define TM_PALETTE_NORMAL 0x192
#define TM_PALETTE_POISON 0x193
#define TM_PALETTE_ICE 0x194
#define TM_PALETTE_GRASS 0x195
#define TM_PALETTE_FIRE 0x196
#define TM_PALETTE_DARK 0x197
#define TM_PALETTE_STEEL 0x198
#define TM_PALETTE_ELECTRIC 0x199
#define TM_PALETTE_GROUND 0x19A
#define TM_PALETTE_GHOST 0x19B
#define TM_PALETTE_ROCK 0x19C
#define TM_PALETTE_FLYING 0x19D
#define TM_PALETTE_BUG 0x262




#endif // POKEPLATINUM_CONSTANTS_PALETTE_H
