species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
darkrai_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('male_back.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '732': files('forms/base/back.png'),
    '733': files('forms/base/front.png'),
    '734': files('forms/mega/back.png'),
    '735': files('forms/mega/front.png'),
    '736': files('forms/base/normal.pal'),
    '737': files('forms/base/shiny.pal'),
    '738': files('forms/mega/normal.pal'),
    '739': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
