species_data_files += files('data.json')
species_data_files += files('forms/mega_x/data.json')
species_data_files += files('forms/mega_y/data.json')

poke_icon_files += files('icon.png')
raichu_mega_x_icon = files('forms/mega_x/icon.png')
raichu_mega_y_icon = files('forms/mega_y/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
        '176': files('forms/base/back.png'),
        '177': files('forms/base/front.png'),
        '178': files('forms/mega_x/back.png'),
        '179': files('forms/mega_x/front.png'),
        '506': files('forms/base/normal.pal'),
        '507': files('forms/base/shiny.pal'),
        '508': files('forms/mega_x/normal.pal'),
        '509': files('forms/mega_x/shiny.pal'),
        '180': files('forms/mega_y/back.png'),
        '181': files('forms/mega_y/front.png'),
        '510': files('forms/mega_y/normal.pal'),
        '511': files('forms/mega_y/shiny.pal'),
}
pokefoot_files += files('footprint.png')
