species_data_files += files('data.json')
species_data_files += files('forms/mega_x/data.json')
species_data_files += files('forms/mega_y/data.json')

poke_icon_files += files('icon.png')
raichu_mega_x_icon = files('forms/mega_x/icon.png')
raichu_mega_y_icon = files('forms/mega_y/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '292': files('forms/base/back.png'),
    '293': files('forms/base/front.png'),
    '294': files('forms/mega_x/back.png'),
    '295': files('forms/mega_x/front.png'),
    '296': files('forms/base/normal.pal'),
    '297': files('forms/base/shiny.pal'),
    '298': files('forms/mega_x/normal.pal'),
    '299': files('forms/mega_x/shiny.pal'),
    '300': files('forms/base/back.png'),
    '301': files('forms/base/front.png'),
    '302': files('forms/mega_y/back.png'),
    '303': files('forms/mega_y/front.png'),
    '304': files('forms/base/normal.pal'),
    '305': files('forms/base/shiny.pal'),
    '306': files('forms/mega_y/normal.pal'),
    '307': files('forms/mega_y/shiny.pal'),
}
pokefoot_files += files('footprint.png')
