species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
mawile_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '524': files('forms/base/back.png'),
    '525': files('forms/base/front.png'),
    '526': files('forms/mega/back.png'),
    '527': files('forms/mega/front.png'),
    '528': files('forms/base/normal.pal'),
    '529': files('forms/base/shiny.pal'),
    '530': files('forms/mega/normal.pal'),
    '531': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
