nwav_sound_files = [
    'SEQ_EMPTY.nwav',
    'SEQ_D_MOUNT1.nwav',
    'SEQ_BATTLE_CHAMPION.nwav',
    'SEQ_BATTLE_WILD_POKEMON.nwav',
    'SEQ_BA_LASTMON.nwav',
    'SEQ_VICTORY_GYM_LEADER.nwav',
    'SEQ_BATTLE_GYM_LEADER.nwav',
    'SEQ_TITLE00.nwav',
    'SEQ_TITLE01.nwav',
    'SEQ_THE_RIV.nwav',
    'SEQ_BA_RIVAL.nwav',
    'SEQ_D_LAKE.nwav',
    'SEQ_D_ROAD_A.nwav',
    'SEQ_TV_HOUSOU.nwav',
    'SEQ_TOWN01_D.nwav',
    'SEQ_OPENING.nwav',
    'SEQ_TOWN02_D.nwav',
    'SEQ_CITY01_D.nwav',
    'SEQ_FS.nwav',
    'SEQ_ROAD_B_D.nwav',
    'SEQ_D_04.nwav',
    'SEQ_BA_TRAIN.nwav',
    'SEQ_GYM.nwav',
    'SEQ_CITY03_D.nwav',
    'SEQ_PC_01.nwav',
    'SEQ_D_05.nwav',
    'SEQ_BLD_TV.nwav',
    'SEQ_PL_HANDSOME.nwav',
    'SEQ_TSURETEKE.nwav',
    'SEQ_BLD_DENDO.nwav',
    'SEQ_THE_GIRL.nwav',
]

foreach f : nwav_sound_files
    nitrofs_files += fs.copyfile(f)
endforeach
