species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
skarmory_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '460': files('forms/base/back.png'),
    '461': files('forms/base/front.png'),
    '462': files('forms/mega/back.png'),
    '463': files('forms/mega/front.png'),
    '464': files('forms/base/normal.pal'),
    '465': files('forms/base/shiny.pal'),
    '466': files('forms/mega/normal.pal'),
    '467': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
