species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')
species_data_files += files('forms/mega_z/data.json')

poke_icon_files += files('icon.png')
absol_mega_icon = files('forms/mega/icon.png')
absol_mega_z_icon = files('forms/mega_z/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '596': files('forms/base/back.png'),
    '597': files('forms/base/front.png'),
    '598': files('forms/mega/back.png'),
    '599': files('forms/mega/front.png'),
    '600': files('forms/base/normal.pal'),
    '601': files('forms/base/shiny.pal'),
    '602': files('forms/mega/normal.pal'),
    '603': files('forms/mega/shiny.pal'),
    '604': files('forms/base/back.png'),
    '605': files('forms/base/front.png'),
    '606': files('forms/mega_z/back.png'),
    '607': files('forms/mega_z/front.png'),
    '608': files('forms/base/normal.pal'),
    '609': files('forms/base/shiny.pal'),
    '610': files('forms/mega_z/normal.pal'),
    '611': files('forms/mega_z/shiny.pal'),
}
pokefoot_files += files('footprint.png')
