#include "battle/mega_evolution.h"
#include "constants/forms.h"
#include "pokemon.h"
#include "generated/items.h"
#include "generated/species.h"
#include "struct_defs/pokemon_mega_data.h"
#include "res/battle/scripts/sub_seq.naix.h"
#include "battle/battle_lib.h"
#include "desmume.h"

const MegaEvolutionData sMegaEvolutionTable[] = {
    {SPECIES_VENUSAUR, VENUSAUR_FORM_MEGA, ITEM_VENUSAURITE},
    {SPECIES_CHARIZARD, CHARIZARD_FORM_MEGA_X, ITEM_CHARIZARDITE_X},
    {SPECIES_CHARIZARD, CHARIZARD_FORM_MEGA_Y, ITEM_CHARIZARDITE_Y},
    {SPECIES_BLASTOISE, BLASTOISE_FORM_MEGA, ITEM_BLASTOISINITE},
    {SPECIES_BEEDRILL, BEEDRILL_FORM_MEGA, ITEM_BEEDRILLITE},
    {SPECIES_PIDGEOT, PIDGEOT_FORM_MEGA, ITEM_PIDGEOTITE},
    {SPECIES_RAICHU, RAICHU_FORM_MEGA_X, ITEM_RAICHUNITE_X},
    {SPECIES_RAICHU, RAICHU_FORM_MEGA_Y, ITEM_RAICHUNITE_Y},
    {SPECIES_CLEFABLE, CLEFABLE_FORM_MEGA, ITEM_CLEFABLITE},
    {SPECIES_ALAKAZAM, ALAKAZAM_FORM_MEGA, ITEM_ALAKAZITE},
    {SPECIES_VICTREEBEL, VICTREEBEL_FORM_MEGA, ITEM_VICTREEBELITE},
    {SPECIES_SLOWBRO, SLOWBRO_FORM_MEGA, ITEM_SLOWBRONITE},
    {SPECIES_GENGAR, GENGAR_FORM_MEGA, ITEM_GENGARITE},
    {SPECIES_KANGASKHAN, KANGASKHAN_FORM_MEGA, ITEM_KANGASKHANITE},
    {SPECIES_STARMIE, STARMIE_FORM_MEGA, ITEM_STARMINITE},
    {SPECIES_PINSIR, PINSIR_FORM_MEGA, ITEM_PINSIRITE},
    {SPECIES_GYARADOS, GYARADOS_FORM_MEGA, ITEM_GYARADOSITE},
    {SPECIES_AERODACTYL, AERODACTYL_FORM_MEGA, ITEM_AERODACTYLITE},
    {SPECIES_DRAGONITE, DRAGONITE_FORM_MEGA, ITEM_DRAGONINITE},
    {SPECIES_MEWTWO, MEWTWO_FORM_MEGA_X, ITEM_MEWTWONITE_X},
    {SPECIES_MEWTWO, MEWTWO_FORM_MEGA_Y, ITEM_MEWTWONITE_Y},
    {SPECIES_MEGANIUM, MEGANIUM_FORM_MEGA, ITEM_MEGANIUMITE},
    {SPECIES_FERALIGATR, FERALIGATR_FORM_MEGA, ITEM_FERALIGITE},
    {SPECIES_AMPHAROS, AMPHAROS_FORM_MEGA, ITEM_AMPHAROSITE},
    {SPECIES_STEELIX, STEELIX_FORM_MEGA, ITEM_STEELIXITE},
    {SPECIES_SCIZOR, SCIZOR_FORM_MEGA, ITEM_SCIZORITE},
    {SPECIES_HERACROSS, HERACROSS_FORM_MEGA, ITEM_HERACRONITE},
    {SPECIES_SKARMORY, SKARMORY_FORM_MEGA, ITEM_SKARMORITE},
    {SPECIES_HOUNDOOM, HOUNDOOM_FORM_MEGA, ITEM_HOUNDOOMINITE},
    {SPECIES_TYRANITAR, TYRANITAR_FORM_MEGA, ITEM_TYRANITARITE},
    {SPECIES_SCEPTILE, SCEPTILE_FORM_MEGA, ITEM_SCEPTILITE},
    {SPECIES_BLAZIKEN, BLAZIKEN_FORM_MEGA, ITEM_BLAZIKENITE },
    {SPECIES_SWAMPERT , SWAMPERT_FORM_MEGA, ITEM_SWAMPERTITE },
    {SPECIES_GARDEVOIR , GARDEVOIR_FORM_MEGA, ITEM_GARDEVOIRITE },
    { SPECIES_SABLEYE , SABLEYE_FORM_MEGA, ITEM_SABLENITE },
 	{ SPECIES_MAWILE , MAWILE_FORM_MEGA, ITEM_MAWILITE },
 	{ SPECIES_AGGRON , AGGRON_FORM_MEGA, ITEM_AGGRONITE },
 	{ SPECIES_MEDICHAM , MEDICHAM_FORM_MEGA ,ITEM_MEDICHAMITE },
 	{ SPECIES_MANECTRIC , MANECTRIC_FORM_MEGA , ITEM_MANECTITE },
 	{ SPECIES_SHARPEDO , SHARPEDO_FORM_MEGA ,ITEM_SHARPEDONITE },
 	{ SPECIES_CAMERUPT , CAMERUPT_FORM_MEGA ,ITEM_CAMERUPTITE },
 	{ SPECIES_ALTARIA , ALTARIA_FORM_MEGA ,ITEM_ALTARIANITE },
 	{ SPECIES_BANETTE , BANETTE_FORM_MEGA ,ITEM_BANETTITE },
 	{ SPECIES_CHIMECHO , CHIMECHO_FORM_MEGA, ITEM_CHIMECHITE },
    {SPECIES_ABSOL , ABSOL_FORM_MEGA, ITEM_ABSOLITE },
    { SPECIES_ABSOL , ABSOL_FORM_MEGA_Z, ITEM_ABSOLITE_Z },
    {SPECIES_GLALIE , GLALIE_FORM_MEGA, ITEM_GLALITITE },
    {SPECIES_SALAMENCE , SALAMENCE_FORM_MEGA, ITEM_SALAMENCITE },
    {SPECIES_METAGROSS , METAGROSS_FORM_MEGA, ITEM_METAGROSSITE },
    {SPECIES_LATIAS , LATIAS_FORM_MEGA, ITEM_LATIASITE },
    {SPECIES_LATIOS , LATIOS_FORM_MEGA, ITEM_LATIOSITE },
    {SPECIES_STARAPTOR , STARAPTOR_FORM_MEGA, ITEM_STARAPTITE },
    {SPECIES_LOPUNNY , LOPUNNY_FORM_MEGA, ITEM_LOPUNNITE },
    {SPECIES_GARCHOMP , GARCHOMP_FORM_MEGA, ITEM_GARCHOMPITE },
    {SPECIES_GARCHOMP , GARCHOMP_FORM_MEGA_Z, ITEM_GARCHOMPITE_Z },
    {SPECIES_LUCARIO , LUCARIO_FORM_MEGA, ITEM_LUCARIONITE },
    {SPECIES_LUCARIO , LUCARIO_FORM_MEGA_Z, ITEM_LUCARIONITE_Z },
    {SPECIES_ABOMASNOW , ABOMASNOW_FORM_MEGA, ITEM_ABOMASITE },
    {SPECIES_GALLADE , GALLADE_FORM_MEGA, ITEM_GALLADITE }, 
    {SPECIES_FROSLASS , FROSLASS_FORM_MEGA, ITEM_FROSLASSITE },
    {SPECIES_HEATRAN , HEATRAN_FORM_MEGA, ITEM_HEATRANITE },
    {SPECIES_DARKRAI , DARKRAI_FORM_MEGA, ITEM_DARKRANITE },
};

BOOL BattleMon_CanMegaEvolve(BattleContext *battleCtx, u8 battler)
{

    if (battleCtx->megaEvolutionUsed[battler])
    {
        return FALSE;
    }

    int species = BattleMon_Get(battleCtx, battler, BATTLEMON_SPECIES, NULL);
    int heldItem = BattleMon_Get(battleCtx, battler, BATTLEMON_HELD_ITEM, NULL);
    int currentForm = BattleMon_Get(battleCtx, battler, BATTLEMON_FORM_NUM, NULL);

    // Cannot mega evolve if already mega evolved
    if (currentForm != 0) {
        return FALSE;
    }

    // Check if this species + item combination exists in the table
    for (int i = 0; i < sizeof(sMegaEvolutionTable) / sizeof(sMegaEvolutionTable[0]); i++) {
        if (sMegaEvolutionTable[i].baseSpecies == species && 
            sMegaEvolutionTable[i].requiredItem == heldItem) {
            return TRUE;
        }
    }

    return FALSE;
}

u16 GetMegaEvolutionData(BattleContext *battleCtx, u8 battler)
{
    int species = BattleMon_Get(battleCtx, battler, BATTLEMON_SPECIES, NULL);
    int heldItem = BattleMon_Get(battleCtx, battler, BATTLEMON_HELD_ITEM, NULL);

    for (int i = 0; i < sizeof(sMegaEvolutionTable) / sizeof(sMegaEvolutionTable[0]); i++) {
        if (sMegaEvolutionTable[i].baseSpecies == species && 
            sMegaEvolutionTable[i].requiredItem == heldItem) {
            return sMegaEvolutionTable[i].megaForm;
        }
    }

    return 0;
}