species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')
species_data_files += files('forms/mega_z/data.json')

poke_icon_files += files('icon.png')
lucario_mega_icon = files('forms/mega/icon.png')
lucario_mega_z_icon = files('forms/mega_z/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
        '364': files('forms/base/back.png'),
        '365': files('forms/base/front.png'),
        '366': files('forms/mega/back.png'),
        '367': files('forms/mega/front.png'),
        '694': files('forms/base/normal.pal'),
        '695': files('forms/base/shiny.pal'),
        '696': files('forms/mega/normal.pal'),
        '697': files('forms/mega/shiny.pal'),
        '368': files('forms/mega_z/back.png'),
        '369': files('forms/mega_z/front.png'),
        '698': files('forms/mega_z/normal.pal'),
        '699': files('forms/mega_z/shiny.pal'),
}
pokefoot_files += files('footprint.png')
