species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
starmie_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('male_back.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '356': files('forms/base/back.png'),
    '357': files('forms/base/front.png'),
    '358': files('forms/mega/back.png'),
    '359': files('forms/mega/front.png'),
    '360': files('forms/base/normal.pal'),
    '361': files('forms/base/shiny.pal'),
    '362': files('forms/mega/normal.pal'),
    '363': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
