species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
venusaur_mega_icon = files('forms/mega/icon.png')
venusaur_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
        '154': files('forms/base/back.png'),
        '155': files('forms/base/front.png'),
        '156': files('forms/mega/back.png'),
        '157': files('forms/mega/front.png'),
        '484': files('forms/base/normal.pal'),
        '485': files('forms/base/shiny.pal'),
        '486': files('forms/mega/normal.pal'),
        '487': files('forms/mega/shiny.pal'),
}

pokefoot_files += files('footprint.png')
