species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
venusaur_mega_icon = files('forms/mega/icon.png')
venusaur_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '138': files('forms/base/back.png'),
    '139': files('forms/base/front.png'),
    '140': files('forms/mega/back.png'),
    '141': files('forms/mega/front.png'),
    '232': files('forms/base/normal.pal'),
    '233': files('forms/base/shiny.pal'),
    '234': files('forms/mega/normal.pal'),
    '235': files('forms/mega/shiny.pal'),
}

otherpoke_index += {
    '244': files('forms/base/back.png'),
    '245': files('forms/base/front.png'),
    '246': files('forms/mega/back.png'),
    '247': files('forms/mega/front.png'),
    '248': files('forms/base/normal.pal'),
    '249': files('forms/base/shiny.pal'),
    '250': files('forms/mega/normal.pal'),
    '251': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
