species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
metagross_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('male_back.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
        '338': files('forms/base/back.png'),
        '339': files('forms/base/front.png'),
        '340': files('forms/mega/back.png'),
        '341': files('forms/mega/front.png'),
        '668': files('forms/base/normal.pal'),
        '669': files('forms/base/shiny.pal'),
        '670': files('forms/mega/normal.pal'),
        '671': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
