species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
slowbro_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '332': files('forms/base/back.png'),
    '333': files('forms/base/front.png'),
    '334': files('forms/mega/back.png'),
    '335': files('forms/mega/front.png'),
    '336': files('forms/base/normal.pal'),
    '337': files('forms/base/shiny.pal'),
    '338': files('forms/mega/normal.pal'),
    '339': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
