species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
glalie_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '612': files('forms/base/back.png'),
    '613': files('forms/base/front.png'),
    '614': files('forms/mega/back.png'),
    '615': files('forms/mega/front.png'),
    '616': files('forms/base/normal.pal'),
    '617': files('forms/base/shiny.pal'),
    '618': files('forms/mega/normal.pal'),
    '619': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
