species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
kangaskhan_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('female_front.png')

otherpoke_index += {
        '202': files('forms/base/back.png'),
        '203': files('forms/base/front.png'),
        '204': files('forms/mega/back.png'),
        '205': files('forms/mega/front.png'),
        '532': files('forms/base/normal.pal'),
        '533': files('forms/base/shiny.pal'),
        '534': files('forms/mega/normal.pal'),
        '535': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
