species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
heracross_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
        '252': files('forms/base/back.png'),
        '253': files('forms/base/front.png'),
        '254': files('forms/mega/back.png'),
        '255': files('forms/mega/front.png'),
        '582': files('forms/base/normal.pal'),
        '583': files('forms/base/shiny.pal'),
        '584': files('forms/mega/normal.pal'),
        '585': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
