species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
alakazam_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
        '186': files('forms/base/back.png'),
        '187': files('forms/base/front.png'),
        '188': files('forms/mega/back.png'),
        '189': files('forms/mega/front.png'),
        '516': files('forms/base/normal.pal'),
        '517': files('forms/base/shiny.pal'),
        '518': files('forms/mega/normal.pal'),
        '519': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
