species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
latios_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('male_back.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
        '346': files('forms/base/back.png'),
        '347': files('forms/base/front.png'),
        '348': files('forms/mega/back.png'),
        '349': files('forms/mega/front.png'),
        '676': files('forms/base/normal.pal'),
        '677': files('forms/base/shiny.pal'),
        '678': files('forms/mega/normal.pal'),
        '679': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
