species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
sceptile_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
        '268': files('forms/base/back.png'),
        '269': files('forms/base/front.png'),
        '270': files('forms/mega/back.png'),
        '271': files('forms/mega/front.png'),
        '598': files('forms/base/normal.pal'),
        '599': files('forms/base/shiny.pal'),
        '600': files('forms/mega/normal.pal'),
        '601': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
