species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
pidgeot_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '284': files('forms/base/back.png'),
    '285': files('forms/base/front.png'),
    '286': files('forms/mega/back.png'),
    '287': files('forms/mega/front.png'),
    '288': files('forms/base/normal.pal'),
    '289': files('forms/base/shiny.pal'),
    '290': files('forms/mega/normal.pal'),
    '291': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
