species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')
species_data_files += files('forms/mega_z/data.json')

poke_icon_files += files('icon.png')
garchomp_mega_icon = files('forms/mega/icon.png')
garchomp_mega_z_icon = files('forms/mega_z/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('male_back.png')
pokegra_files += files('female_front.png')
pokegra_files += files('male_front.png')

otherpoke_index += {
    '668': files('forms/base/back.png'),
    '669': files('forms/base/front.png'),
    '670': files('forms/mega/back.png'),
    '671': files('forms/mega/front.png'),
    '672': files('forms/base/normal.pal'),
    '673': files('forms/base/shiny.pal'),
    '674': files('forms/mega/normal.pal'),
    '675': files('forms/mega/shiny.pal'),
    '678': files('forms/mega_z/back.png'),
    '679': files('forms/mega_z/front.png'),
    '682': files('forms/mega_z/normal.pal'),
    '683': files('forms/mega_z/shiny.pal'),
}
pokefoot_files += files('footprint.png')
