species_data_files += files('data.json')
species_data_files += files('forms/mega/data.json')

poke_icon_files += files('icon.png')
froslass_mega_icon = files('forms/mega/icon.png')

pokegra_files += files('female_back.png')
pokegra_files += files('female_front.png')

otherpoke_index += {
    '716': files('forms/base/back.png'),
    '717': files('forms/base/front.png'),
    '718': files('forms/mega/back.png'),
    '719': files('forms/mega/front.png'),
    '720': files('forms/base/normal.pal'),
    '721': files('forms/base/shiny.pal'),
    '722': files('forms/mega/normal.pal'),
    '723': files('forms/mega/shiny.pal'),
}
pokefoot_files += files('footprint.png')
